import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const xboxFont= localFont({
  src: './fonts/Conv.ttf'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={xboxFont.className}
      >
        {children}
      </body>
    </html>
  );
}
